### PR TITLE
Remove Client Theme

### PR DESCRIPTION
**Pull request by CodeF53**
I do not approve of this fork and would like to remove my plugin.

### CODE REVIEW

**Comment by cutekita** [comment]
Haven't you licensed your code under GPL-3 when committing it to Vencord, thus allowing forks and edits? or am I misunderstanding something here?

**Comment by CodeF53** [comment]
> Haven't you licensed your code under GPL-3 when committing it to Vencord, thus allowing forks and edits? or am I misunderstanding something here?

Sure they *can* fork and edit. Nothing is stopping me from asking nicely to be removed because their mod isn't cute.

**Comment by cutekita** [comment]
I wouldn't disagree with the facts. I believe your first message sounded more like a demand rather than a request, which to me seemed like betting on the maintainers not knowing their rights.

**Comment by thororen1234** [comment]
> > Haven't you licensed your code under GPL-3 when committing it to Vencord, thus allowing forks and edits? or am I misunderstanding something here?
> 
> Sure they _can_ fork and edit. Nothing is stopping me from asking nicely to be removed because their mod isn't cute.

I would prefer to not remove it as it is an actual plugin in vencord and people will get angry but any specific reason you want it removed?

**Comment by thororen1234** [comment]
Also I don't think "their mod isn't cute" is a good reason at all.

**Comment by thororen1234** [comment]
Closing this as we do not plan to remove this plugin from our fork as we try to maintain as close to actual vencord as we can with their plugins.

**Comment by Yeetov** [comment]
It is CodeF53's plugin so I think you should respect their wishes.

**Comment by vMohammad24** [comment]
#JusticeForcoolesding

**Pull request closed without merging**
