### PR TITLE
Add HideServers

### PR DESCRIPTION
**Pull request by bepvte**
Small plugin that adds a context menu option to hide specific servers from the guilds list and quick switcher

### CODE REVIEW

**Comment by thororen1234** [comment]
This all good to go?

**Comment by bepvte** [comment]
Ya

**Comment by verticalsync** [comment]
> Ya

you shouldnt add yourself to `Devs`, but `EquicordDevs` instead

**Comment by bepvte** [comment]
It looks like vencord is interested in it again, so closing here and responding to the mr comments there https://github.com/Vendicated/Vencord/pull/2370

**Comment by refurbishing** [comment]
> It looks like vencord is interested in it again, so closing here and responding to the mr comments there [Vendicated#2370](https://github.com/Vendicated/Vencord/pull/2370)

this aged like milk

**Pull request closed without merging**
