### PR TITLE
feat(Settings): update join buttons

### PR DESCRIPTION
**Pull request by KrstlSkll69**
update the button to look better

watermark

### CODE REVIEW

**Comment by KrstlSkll69** [comment]
i also went in and applied the `(border-radius: 5px;)` to the `Disable All Plugins` button

**Comment by KrystalSkullOfficial** [comment]
At thororens request switched them back to be on one line



Also made some variables for the dono button _(let me cook)_

**Comment by KrstlSkll69** [comment]
At thororens request switched them back to be on one line



Also made some variables for the dono button _(let me cook)_

**Comment by KrstlSkll69** [comment]
added noticeable warning for `window transparency`. Also renamed the file because that name makes more sense.

**Pull request merged**
