### PR TITLE
feat(plugin): Stickers+

### PR DESCRIPTION
**Pull request by lekoOwO**
This plugin allows user send stickers from more sticker providers.
Currently LINE and self-made stickerpack files supported.

Inspired by https://github.com/Pitu/Magane .

### CODE REVIEW

**Comment by KrystalSkullOfficial** [comment]
plugins meant for Equicord, belong in src/equicordplugins

**Comment by KrystalSkullOfficial** [comment]
Also change to the `constants.ts` file need to be done after line `582`

**Comment by refurbishing** [comment]
Is there any good reason why this plugin needs ffmpeg and 20+ files to function?
It seems that this will be kinda be difficult and time-consuming to maintain.

**Comment by thororen1234** [comment]
@lekoOwO first if I have permission to modify this prs code I will be merging some things second I will not be maintaining this for you. If you agree to maintaining it then I will merge it and once you stop maintaining it it will either be dropped or locked to dev until fixed what do you say?

**Comment by thororen1234** [comment]
Time between it breaking and going to dev or dropped would be 2-3 weeks.

**Comment by lekoOwO** [comment]
That sounds good to me :)

**Comment by lekoOwO** [comment]
> Is there any good reason why this plugin needs ffmpeg and 20+ files to function? It seems that this will be kinda be difficult and time-consuming to maintain.

Well at first ffmpeg wasn't in the plan of this project, until animated stickers occurred and someday I kinda have a "good" idea to make it front-end convertible to GIF to keep it animated and preserve the transparency details :)

As for the "20+ files", well, it's kinda like a small app in Discord TBH. There are no redundant codes if we review it deeply. The main reason is that we can't just take the Discord UI Components and use it like a SDK (at least I don't see the the possibilities, maybe i missed sth though) so I have to re-invent the wheels to make the UI and Components pretty like the official ones. 
Also, I have to define the data structures of the stickers to conform w/ many sticker sources, consider the persistency and the ease of accessbility, sticker scraping and parsing, import and export, etc. That's why there are so many files for this plugin.

**Comment by thororen1234** [comment]
@lekoOwO are you able to fork this as equicord instead of vencord? it would be stop a second commit needing to be made for fixes.

**Comment by lekoOwO** [comment]
Sure, will re-open a PR once it's done

Edit: oh i do not need to do that. I can change the base branch of the PR :)

**Comment by thororen1234** [comment]
Thanks! also if your trying to keep your original vencord repo just fork equicord to a random org if you have one for example a dump org for forking projects.

**Comment by thororen1234** [comment]
or use git commands which I have no reference for.

**Comment by lekoOwO** [comment]
Replaced by https://github.com/Equicord/Equicord/pull/66

**Pull request closed without merging**
