### PR TITLE
Main

### PR DESCRIPTION
**Pull request by zyqunix**

### CODE REVIEW

**Review by zyqunix — COMMENTED** [review]
plz dont kill this is my first pr and plugin 😭

**Comment by vMohammad24** [comment]
A lot of bots have this functionality, and most of them support user-installable commands.

**Comment by zyqunix** [comment]
what if you don't want to use a bot and want to directly send the gif in DMs/channel?

**Comment by vMohammad24** [comment]
This uses 5 extra packages just for one command, meaning for everyone that isn't using it, its just more bloat

**Comment by broduer** [comment]
-1

**Pull request closed without merging**
