### PR TITLE
Added two plugins

### PR DESCRIPTION
**Pull request by example-git**
ported a modified version of VCNarrator that uses the tiktok voice, and created a plugin named FurudoSpeak. A modification of the shakespearean plugin but uses openai as its base and implements more flexibility on the character speech patterns. It requires an api keys to use though.

### CODE REVIEW

**Comment by KrystalSkullOfficial** [comment]
remove the constant from the vencord side of the file

**Comment by example-git** [comment]
My B, wasn't sure how to handle creditiing a ported plugin from a fork of Vencord. Fixed it

**Comment by KrystalSkullOfficial** [comment]
Thats fine, also please add the plugins to the readme.md file. Also please add `.dev` to the end of the file _(such has the original `shakeSpearean` plugin is)_ has the same rules about it needing a Api key still apply

**Comment by example-git** [comment]
Knocked that change out, lemme know if there's anything else you want me to change. I don't contribute to a ton of projects so apologies for any headaches.

**Pull request merged**
