### PR TITLE
Update index.tsx (TESt)

### PR DESCRIPTION
**Pull request by KrstlSkll69**

### CODE REVIEW

**Comment by KrstlSkll69** [comment]
damn

**Comment by thororen1234** [comment]
fun times

**Comment by thororen1234** [comment]
it will rerun this way btw

**Comment by KrstlSkll69** [comment]
bro is blowing up my email rn

**Comment by thororen1234** [comment]
> bro is blowing up my email rn

mb but it worked ty

**Comment by KrstlSkll69** [comment]
> > bro is blowing up my email rn
> 
> mb but it worked ty

say less, just try not to break github again please

**Pull request closed without merging**
