### PR TITLE
Update Translate+

### PR DESCRIPTION
**Pull request by Prince527GitHub**
Ive been thinking about Shavian ❤️ and about how to keep it in without like 4 MB of json.

Then suddenly, it hit me, load the json from the web 🤦 which brings me to this PR.

(I don't know how to write in Shavian, cant understand a single word)

### CODE REVIEW

**Comment by LMacrini** [comment]
this ain't a language bruh

**Comment by Prince527GitHub** [comment]
I'm making this a draft because I want to fix a big oversight.

Which is that changing the language does nothing, like a user cant go from Shavian to French or Toki Pona to Russian.

**Comment by Prince527GitHub** [comment]
Welp time to add types

**Comment by Prince527GitHub** [comment]
Nice it passed testing

**Comment by Prince527GitHub** [comment]
Alright so il explain what ive changed.

- Refactored almost the entire plugin
- Load Shavian & Sitelen Pona dictionary from the web
- Added Sitelen Pona support (see image below)
- Added support for translating to other langs (ex: Shavian -> French) (see image below)
- Changed description
- Added a new icon (see image below)

Sitelen Pona
Other lang support
New icon

**Comment by Prince527GitHub** [comment]
I think its ready now, so let me know if there are any changes needed :)

**Review by thororen1234 — APPROVED** [review]
lgtm

**Pull request merged**
